# Automatically generated using Clang.jl


const SRWLOCK_INIT = RTL_SRWLOCK_INIT
const INIT_ONCE_STATIC_INIT = RTL_RUN_ONCE_INIT
const INIT_ONCE_CHECK_ONLY = RTL_RUN_ONCE_CHECK_ONLY
const INIT_ONCE_ASYNC = RTL_RUN_ONCE_ASYNC
const INIT_ONCE_INIT_FAILED = RTL_RUN_ONCE_INIT_FAILED
const INIT_ONCE_CTX_RESERVED_BITS = RTL_RUN_ONCE_CTX_RESERVED_BITS
const CONDITION_VARIABLE_INIT = RTL_CONDITION_VARIABLE_INIT
const CONDITION_VARIABLE_LOCKMODE_SHARED = RTL_CONDITION_VARIABLE_LOCKMODE_SHARED
const MUTEX_MODIFY_STATE = MUTANT_QUERY_STATE
const MUTEX_ALL_ACCESS = MUTANT_ALL_ACCESS

# Skipping MacroDefinition: OpenEvent __MINGW_NAME_AW ( OpenEvent )

const SYNCHRONIZATION_BARRIER_FLAGS_SPIN_ONLY = 0x01
const SYNCHRONIZATION_BARRIER_FLAGS_BLOCK_ONLY = 0x02
const SYNCHRONIZATION_BARRIER_FLAGS_NO_DELETE = 0x04

# Skipping MacroDefinition: CreateMutex __MINGW_NAME_AW ( CreateMutex )
# Skipping MacroDefinition: CreateEvent __MINGW_NAME_AW ( CreateEvent )

const SRWLOCK = RTL_SRWLOCK
const PSRWLOCK = Ptr{RTL_SRWLOCK}
const INIT_ONCE = RTL_RUN_ONCE
const PINIT_ONCE = PRTL_RUN_ONCE
const LPINIT_ONCE = PRTL_RUN_ONCE
const PINIT_ONCE_FN = Ptr{Cvoid}
const CONDITION_VARIABLE = RTL_CONDITION_VARIABLE
const PCONDITION_VARIABLE = Ptr{RTL_CONDITION_VARIABLE}
const PTIMERAPCROUTINE = Ptr{Cvoid}
const SYNCHRONIZATION_BARRIER = RTL_BARRIER
const PSYNCHRONIZATION_BARRIER = PRTL_BARRIER
const LPSYNCHRONIZATION_BARRIER = PRTL_BARRIER
